/**
 * Per-network on-chain address book.
 *
 * These constants mirror `deployments/v1/<network>.json` in the repo and are the
 * SDK's baked-in defaults. They are intended to be regenerated by a codegen step
 * in CI so a redeploy updates the SDK with a single command. Callers may override
 * any address through {@link OpaqueConfig}.
 */
import type { OpaqueNetwork } from "./networks";

export interface ContractAddresses {
  stealthRegistry: string;
  stealthAnnouncer: string;
  groth16Verifier: string;
  reputationVerifier: string;
  schemaRegistry: string;
  attestationEngineV2: string;
  poolVerifier: string;
  privacyPool: string;
  relayerRegistry: string;
  /**
   * Optional: not yet deployed on any network (see `deployments/v1/*.json`'s
   * `"multisig": null`). Set once deployed to enable {@link OpaqueClient.contracts.multisigAdmin}.
   */
  multisigAdmin?: string;
}

export interface PoolWiring {
  /** Domain separator bound into pool commitments. */
  scope: number;
  /** Native XLM Stellar Asset Contract id backing the pool. */
  nativeSac: string;
}

export interface RelayerWiring {
  minimumStake: bigint;
  unstakeCooldownLedgers: number;
  maxDeadlineLedgers: number;
  gatewayUrls: string[];
}

export interface ContractVersions {
  stealthRegistry: number;
  stealthAnnouncer: number;
  groth16Verifier: number;
  reputationVerifier: number;
  schemaRegistry: number;
  attestationEngineV2: number;
  poolVerifier: number;
  privacyPool: number;
  relayerRegistry: number;
}

export interface NetworkDeployment {
  contracts: ContractAddresses;
  pool: PoolWiring;
  relayer: RelayerWiring;
  /** Expected contract interface versions at this deployment. */
  contractVersions?: ContractVersions;
  /** Ledger the contracts were deployed at; event scans start here. */
  deploymentLedger: number;
}

/** Generated from deployments/v1/testnet.json. */
export const TESTNET_DEPLOYMENT: NetworkDeployment = {
  contracts: {
    stealthRegistry: "CAIXWMGYZR3YAQ3CPCXOU42WG62E3ARUSG4GDHHDMNRXUD44YSGE5VXW",
    stealthAnnouncer: "CB2Y3GJMPY5BUSZLXG3DSIMERCNCTUM63IIEQ2GUNYEJ3DBKPFIZQGCS",
    groth16Verifier: "CAWXRGFZITZ7TJIZNDLOPJNVEMPAZDWFI22XI76FC67YF2MDRUXLBS2T",
    reputationVerifier: "CAFVXL6A5N4FVQZ733GLUX27ETPLLINLE75ZABNLFYEKPIYZORFCBSVR",
    schemaRegistry: "CA5XA2T2DAOZH7QG5RG2372KGDHMCEVQJMBGT7AJMNHRI6C4ZIM37QCP",
    attestationEngineV2: "CB6KOWOQBFQDX5NNGUJGECHXUF3LHUE77FYD2C6JSWMHYWGCJOUTSDPX",
    poolVerifier: "CBWHOATL5TQLQNIOJ3EADOQ55SH7C3A5OO5BJNJZICBMXXH5NMMDIDFC",
    privacyPool: "CCXNSBVFTVCVUGBZG2RRT2OVVY5ERXGTNYE5DCALAEAROD2IEGJZ7J3J",
    relayerRegistry: "CBTHQFGGDJMEML267U5EGQPYFLARO6TO4QYSK6CVKXWY2TR4DJ7GQ3ND",
  },
  contractVersions: {
    stealthRegistry: 1,
    stealthAnnouncer: 1,
    groth16Verifier: 1,
    reputationVerifier: 1,
    schemaRegistry: 1,
    attestationEngineV2: 1,
    poolVerifier: 1,
    privacyPool: 1,
    relayerRegistry: 1,
  },
  pool: {
    scope: 1,
    nativeSac: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  },
  relayer: {
    minimumStake: 1_000_000n,
    unstakeCooldownLedgers: 720,
    maxDeadlineLedgers: 17280,
    gatewayUrls: ["https://g-stelar-relayer.opaque.cash"],
  },
  deploymentLedger: 3_264_903,
};

/** Known deployments by network. Testnet is the only live deployment today. */
export const DEPLOYMENTS: Partial<Record<OpaqueNetwork, NetworkDeployment>> = {
  testnet: TESTNET_DEPLOYMENT,
};
