// @ts-nocheck
/**
 * Regenerates `sdk/src/config/addresses.ts` from `deployments/v1/*.json`.
 *
 * The deployment manifests are the source of truth for on-chain contract IDs.
 * After every redeploy the updated manifest is committed; this script keeps the
 * SDK's baked-in address constants in sync so callers get the right defaults.
 *
 * Usage:
 *   npx tsx scripts/generate-sdk-addresses.ts          # write file
 *   npx tsx scripts/generate-sdk-addresses.ts --check   # CI gate: fail on drift
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const MANIFESTS_DIR = join(ROOT, "deployments", "v1");
const OUTPUT = join(ROOT, "sdk", "src", "config", "addresses.ts");

const CONTRACT_KEYS = [
  "stealthRegistry",
  "stealthAnnouncer",
  "groth16Verifier",
  "reputationVerifier",
  "schemaRegistry",
  "attestationEngineV2",
  "poolVerifier",
  "privacyPool",
  "relayerRegistry",
] as const;

const INITIAL_VERSIONS: Record<string, number> = Object.fromEntries(
  CONTRACT_KEYS.map((k) => [k, 1]),
);

function loadManifests() {
  const files = readdirSync(MANIFESTS_DIR).filter((f) => f.endsWith(".json"));
  return files.map((file) =>
    JSON.parse(readFileSync(join(MANIFESTS_DIR, file), "utf-8")),
  );
}

/** Format a number with underscore separators: 3264903 → 3_264_903 */
function fmtNum(n: number): string {
  return n.toLocaleString("en-US").replace(/,/g, "_");
}

function generate() {
  const manifests = loadManifests();
  const deployed = manifests.filter(
    (m) => m.deploymentStatus === "deployed",
  );

  if (deployed.length === 0) {
    console.error("No deployed networks found in deployments/v1/*.json");
    process.exit(1);
  }

  const out: string[] = [];

  // ── header ────────────────────────────────────────────────────────────
  out.push(
    "/**",
    " * Per-network on-chain address book.",
    " *",
    " * These constants mirror `deployments/v1/<network>.json` in the repo and are the",
    " * SDK's baked-in defaults. They are intended to be regenerated by a codegen step",
    " * in CI so a redeploy updates the SDK with a single command. Callers may override",
    " * any address through {@link OpaqueConfig}.",
    " */",
    'import type { OpaqueNetwork } from "./networks";',
    "",
  );

  // ── interfaces ────────────────────────────────────────────────────────
  out.push("export interface ContractAddresses {");
  for (const key of CONTRACT_KEYS) out.push(`  ${key}: string;`);
  out.push("}", "");

  out.push("export interface PoolWiring {");
  out.push("  /** Domain separator bound into pool commitments. */");
  out.push("  scope: number;");
  out.push("  /** Native XLM Stellar Asset Contract id backing the pool. */");
  out.push("  nativeSac: string;");
  out.push("}", "");

  out.push("export interface RelayerWiring {");
  out.push("  minimumStake: bigint;");
  out.push("  unstakeCooldownLedgers: number;");
  out.push("  maxDeadlineLedgers: number;");
  out.push("  gatewayUrls: string[];");
  out.push("}", "");

  out.push("export interface ContractVersions {");
  for (const key of CONTRACT_KEYS) out.push(`  ${key}: number;`);
  out.push("}", "");

  out.push("export interface NetworkDeployment {");
  out.push("  contracts: ContractAddresses;");
  out.push("  pool: PoolWiring;");
  out.push("  relayer: RelayerWiring;");
  out.push("  /** Expected contract interface versions at this deployment. */");
  out.push("  contractVersions?: ContractVersions;");
  out.push(
    "  /** Ledger the contracts were deployed at; event scans start here. */",
  );
  out.push("  deploymentLedger: number;");
  out.push("}", "");

  // ── per-network deployment constants ──────────────────────────────────
  for (const manifest of deployed) {
    const constName = `${manifest.network.toUpperCase()}_DEPLOYMENT`;
    out.push(
      `/** Generated from deployments/v1/${manifest.network}.json. */`,
      `export const ${constName}: NetworkDeployment = {`,
    );

    // contracts
    out.push("  contracts: {");
    for (const key of CONTRACT_KEYS) {
      out.push(`    ${key}: "${manifest.contracts[key].id}",`);
    }
    out.push("  },");

    // contractVersions
    out.push("  contractVersions: {");
    for (const key of CONTRACT_KEYS) {
      out.push(`    ${key}: ${INITIAL_VERSIONS[key]},`);
    }
    out.push("  },");

    // pool wiring (from wiring.privacyPool)
    const poolWiring = manifest.wiring?.privacyPool;
    if (poolWiring) {
      out.push("  pool: {");
      out.push(`    scope: ${poolWiring.scope},`);
      out.push(`    nativeSac: "${poolWiring.nativeSac}",`);
      out.push("  },");
    }

    // relayer wiring (from wiring.relayerRegistry)
    const relayerWiring = manifest.wiring?.relayerRegistry;
    if (relayerWiring) {
      out.push("  relayer: {");
      out.push(`    minimumStake: ${fmtNum(relayerWiring.minimumStake)}n,`);
      out.push(
        `    unstakeCooldownLedgers: ${relayerWiring.unstakeCooldownLedgers},`,
      );
      out.push(
        `    maxDeadlineLedgers: ${relayerWiring.maxDeadlineLedgers},`,
      );
      out.push(
        `    gatewayUrls: ${JSON.stringify(relayerWiring.gatewayUrls ?? [])},`,
      );
      out.push("  },");
    }

    // deploymentLedger
    out.push(`  deploymentLedger: ${fmtNum(manifest.deploymentLedger)},`);
    out.push("};", "");
  }

  // ── DEPLOYMENTS record ────────────────────────────────────────────────
  out.push(
    "/** Known deployments by network. Testnet is the only live deployment today. */",
    "export const DEPLOYMENTS: Partial<Record<OpaqueNetwork, NetworkDeployment>> = {",
  );
  for (const manifest of deployed) {
    out.push(
      `  ${manifest.network}: ${manifest.network.toUpperCase()}_DEPLOYMENT,`,
    );
  }
  out.push("};", "");

  return out.join("\n");
}

function main() {
  const checkMode = process.argv.includes("--check");
  const output = generate();

  if (checkMode) {
    const existing = readFileSync(OUTPUT, "utf-8");
    if (existing !== output) {
      console.error(
        "SDK address constants differ from deployment manifests. Run:\n" +
          "  npx tsx scripts/generate-sdk-addresses.ts",
      );
      process.exit(1);
    }
    console.log("SDK address constants are up to date.");
  } else {
    writeFileSync(OUTPUT, output);
    console.log(`Generated ${OUTPUT}`);
  }
}

main();
